version: 2

sources:
    - name: staging
      database: jp-dte-340802
      schema: trips_data_all

      tables:
        - name: green_tripdata_external_table
        - name: yellow_tripdata_external_table
        